//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relacion1a1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int IdEmpleado { get; set; }
        public string Calle { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
